CREATE TABLE "users" (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"email" TEXT NOT NULL UNIQUE, 
	"password" TEXT NOT NULL,
	"createdAt" TIME WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "urls" (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL REFERENCES "users"("id"),
	"shortURL" TEXT NOT NULL,
	"url" TEXT NOT NULL,
	"visitCount" INTEGER NOT NULL DEFAULT 0,
	"createdAt" TIME WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "sessions" (
	"id" SERIAL PRIMARY KEY,
	"token" TEXT NOT NULL,
	"userId" INTEGER NOT NULL REFERENCES "users"("id"), 
	"isActive" bool NOT NULL DEFAULT true,
	"createdAt" TIME WITH TIME ZONE NOT NULL DEFAULT NOW()
);